### ISSUE TITLE
[Non issue] Hello, I am just trying to learn more about competitive programming.

### ISSUE THREAD

**Issue by MayCXC** [petertseng/adventofcode-rb-2020#1]
I noticed you are screaming through AOC again this year. So far, even in problems where my fingers never stop typing, and my first submission passes, I have placed just shy of 1000th. If you don't mind, what would you say the biggest bottleneck is in fast problem solving? Do you have a silver bullet approach to it, or have you made gradual improvements with experience?
Thanks for reading.

Here's a pretty good type system btw:
![image](https://user-images.githubusercontent.com/9441877/101239845-ec396980-36b8-11eb-828f-ad4090acdfa2.png)

**Comment by petertseng** [comment]
Thanks for your inquiry and for the type system!

I can't say there's a silver bullet, but my top two suggestions are knowing the language and its standard libraries well, and knowing yourself so you can manage risk.
And then I'll say a quick word on tooling, and further reading.

**Knowing language and standard libraries**

Although I think you will find that a lot of the fastest solvers have chosen a scripting language, the highest scorer from 2016 used Java, so a scripting language is not a must.
Much more important is knowing the language well enough that you can quickly do what you want to do in it.

For example, day 1 asked us to find two numbers that sum to 2020.
To examine every pair of numbers in a list, I knew that I can use [Array#combination](https://ruby-doc.org/core-2.7.2/Array.html) to do that.
If I instead needed to look it up, or needed to manually write two loops to do it manually by indexing into the array, that would have taken time.

What parts of the language are most important to know will depend a bit on the language and how one tends to express concepts in that language, but for me the highest-value part of Ruby to know was [Enumerable](https://ruby-doc.org/core-2.7.2/Enumerable.html).
Were I doing it in Scala I would want to know [Iterator](https://www.scala-lang.org/api/2.12.1/scala/collection/Iterator.html), and for Rust, their [Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html).

Beyond the capabilities provided by the language, I have a few extras that are not in the language's standard library but that were useful in past Advents of Code.
The most important one is a graph search (BFS); everything else is sort of niche.
I have a few small things written for movements in 2d grids (things like "turn left", "turn right", "move one space in this direction") but in the heat of the moment I don't always remember to use them.

**Knowing yourself and managing risk**

This most obviously comes up when deciding whether to double-check your work before submitting it.
If you made a mistake, then double-checking will cost you a few seconds but save you from the one-minute cooldown.
If you didn't make a mistake but double-check anyway, you wasted those few seconds for no benefit.
So that means the expected value of double-checking depends on the probability you made a mistake, so you can only evaluate this by understanding how likely you are to make a mistake for a given problem.

Another time this can come up is deciding how fast to read the problem.

There are some days (usually the early ones) where the way to be fast is to read as little of the problem as possible.
For example, on this year's day 1 part 1, the entire story is extraneous and you only need to read the bolded sentence: "Find the two entries that sum to 2020; what do you get if you multiply them together?"

On the other hand, there are some days where must read carefully, lest you miss an important detail.
Of the five days that have been released so far this year, day 3 fits this category most closely.
In fact, I was slowed down by about 10 minutes on day 3 part 2 because I missed an important detail when reading!
So that was quite a big bottleneck.

However, part of the challenge is figuring out which category a given day lands in, and that is not easy to do.
There's no easy solution to this one, but I think knowing yourself also helps here, because you'd want to read more carefully in areas where you're more likely to make a mistake.

Finally, knowing yourself also comes in handy when debugging - you'll want to know what are the most likely places the bug could be, and this could be because the algorithm was tricky, or it could just be because you know it's an area you're not confident in.
Some of my biggest slowdowns were when I refused to believe that my code could have a bug (wrong!) or I didn't even consider that the bug could be hiding in a function that I had taken for granted that I could write correctly.

**Tooling and preparation**

Having a script to download the input can save a few seconds.
On days when the leaderboard fills in a few minutes, a few seconds is quite valuable.
I must stress that input-downloading scripts must only download the input once and save it to disk, instead of re-downloading it every time they're run, otherwise that is wasting your own time and also Eric's bandwidth.

Being able to submit programmatically is less helpful and I went without it for many years, so that one is more up to preference.

I have a small template file with useful imports and commented-out code for common things I might want to do (read each line of input into an array, read all numbers of each line into one array of numbers for each line, read each line of input and split by commas, the aforementioned graph search, etc.).
I'm not ready to show the Ruby one, but the Haskell one is at [00_template.hs](https://github.com/petertseng/adventofcode-hs-2020/blob/master/bin/00_template.hs) and I use [mkday.rb](https://github.com/petertseng/adventofcode-hs-2020/blob/master/mkday.rb) to copy it to a new file for every day and set up the build system to be able to build it.

**Further reading**

If you haven't already seen, someone asked a similar question on the subreddit, and a list of past answers was posted in response: https://www.reddit.com/r/adventofcode/comments/k72fzv/how_the_hell_do_you_solve_this_so_fast_day_5_took/geoe4dk/

Overall I think this whole idea of being able to code quickly isn't necessarily that important because in my job they mainly care if I can write it correctly, not write it quickly, but I still do it because it's interesting to see how I compare.
And my coworker did point out that coding fast can be useful if things are on fire.
But overall, I don't stress too much if it turns out I don't stack up.

**Comment by MayCXC** [comment]
Thank you for this response - exactly the information I was looking for. I will definitely brush up on iterator, stream, and scala collections. Still, most of the methods you mentioned are familiar to me, so I think there is still something to be said for brain latency... And thank you for the reassurance about the lack of professional carryover, but I see no need to diminish the spirit of competition, and the clear evidence that some have mastered the rapid programming skillset on a higher level than others. Most of the leaderboard seems to also show a great deal of talent in their long term programming projects, even if they are a small group. Hopefully I will see triple digits in the days to come, cheers.
